"""add rep_name to quote for deal health dashboard

Revision ID: 210693be13d1
Revises: aae8c18f0678
Create Date: 2026-09-05 17:12:41.821748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210693be13d1'
down_revision: Union[str, Sequence[str], None] = 'aae8c18f0678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('rep_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'rep_name')
    # ### end Alembic commands ###
