"""add warehouse, stock, and fulfillment models

Revision ID: 4a96ff0ad2dd
Revises: c3b0c8117107
Create Date: 2026-09-05 16:00:51.909263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a96ff0ad2dd'
down_revision: Union[str, Sequence[str], None] = 'c3b0c8117107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shipping_cost_weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', name='uq_stock_warehouse_product')
    )
    op.create_table('fulfillment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('suggested', 'confirmed', 'manually_overridden', name='fulfillmentplanstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fulfillment_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fulfillment_plan_id', sa.Integer(), nullable=False),
    sa.Column('quote_line_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('quantity_fulfilled', sa.Integer(), nullable=False),
    sa.Column('is_backorder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fulfillment_plan_id'], ['fulfillment_plans.id'], ),
    sa.ForeignKeyConstraint(['quote_line_id'], ['quote_lines.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fulfillment_splits')
    op.drop_table('fulfillment_plans')
    op.drop_table('stocks')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
