"""add product pairing model for upsell suggestions

Revision ID: 600727009389
Revises: 4a96ff0ad2dd
Create Date: 2026-09-05 16:32:17.763025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600727009389'
down_revision: Union[str, Sequence[str], None] = '4a96ff0ad2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_pairings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_product_id', sa.Integer(), nullable=False),
    sa.Column('suggested_product_id', sa.Integer(), nullable=False),
    sa.Column('co_purchase_score', sa.Float(), nullable=False),
    sa.Column('is_promoted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['base_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['suggested_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_pairings')
    # ### end Alembic commands ###
