"""add approval workflow fields and ApprovalAction model

Revision ID: c3b0c8117107
Revises: 42f08f46c319
Create Date: 2026-09-05 12:51:14.554703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b0c8117107'
down_revision: Union[str, Sequence[str], None] = '42f08f46c319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('quotes', sa.Column('required_approval_level', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('current_approval_step', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('risk_reasons', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'risk_reasons')
    op.drop_column('quotes', 'current_approval_step')
    op.drop_column('quotes', 'required_approval_level')
    op.drop_table('approval_actions')
    # ### end Alembic commands ###
